config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  resources :movie_shops, only: [:index, :show] do
    resources :reviews, only: [:index, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie_shop.rb
class MovieShop < ApplicationRecord
  has_many :reviews, dependent: :destroy

  def avg_score 
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end
  def review_score_percentage 
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie_shop
  validates :score, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '2222'
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/movie_shops_controller.rb
class MovieShopsController < ApplicationController
before_action :authenticate_user!, only: [:show]

  def index
    @movie_shops = MovieShop.all
  end

  def show
    @movie_shop = MovieShop.find(params[:id])
    @review = Review.new
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def index
    @movie_shop = MovieShop.find(params[:movie_shop_id])
    @reviews = @movie_shop.reviews
  end

  def create
    @review = Review.new(review_params)
    @review.user_id =current_user.id
    if @review.save
      redirect_to movie_shop_reviews_path(@review.movie_shop)
    else
      @movie_shop = MovieShop.find(params[:id])
      render "movie_shops/show"
    end
  end

  private
  def review_params
    params.require(:review).permit(:movie_shop_id, :score, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movie_shops_helper.rb
module MovieShopsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/homes/top.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-10">
          <p class="is-size-1 has-text-weight-bold has-text-centered">レビューを待っています</p>
          <br>
          <div class="columns is-centered">
            <div class="column is-3">
              <%= link_to "ログイン", new_user_session_path, class: "button is-fullwidth" %>
              <br>
              <%= link_to "新規登録", new_user_registration_path, class: "button is-fullwidth" %>
            </div>
          </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/484e6509e8.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
        <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <p class="navbar-item">
          <%= link_to root_path do %>
            <strong class="is-size-3" style="font-family: cursive; color: black;">movie review</strong>
          <% end %>
        </p>
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to movie_shops_path, class: "navbar-item" do %>
            映画一覧
          <% end %>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <% if user_signed_in? %>
              <p class="navbar-item">おかえりなさい <%= current_user.username %> 様</p>
            <% end %>
            <div class="buttons">
              <% if user_signed_in? %>
                <%= link_to destroy_user_session_path, method: :delete, class: "button" do %>
                  ログアウト
                <% end %>
              <% else %>
                <%= link_to new_user_session_path, class: "button" do %>
                  ログイン
                <% end %>
                <%= link_to new_user_registration_path, class: "button" do %>
                  新規登録
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/movie_shops/index.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <% @movie_shops.each do |movie_shop| %>
          <%= movie_shop.name %>
          <div class="card mb-6">
         <header class="card-header">
    <p class="card-header-title">
      <%= movie_shop.name %>
    </p>
  </header>
  <div class="card-content">
    <div class="content">
      <div class="content average-score">
        <div class="star-rating mb-2">
          <div class="star-rating-front" style="width: <%= movie_shop.review_score_percentage %>%">★★★★★</div>
          <div class="star-rating-back">★★★★★</div>
        </div>
        <div class="average-score-display ml-3 pt-2">
          <%= movie_shop.avg_score %>点（<%= movie_shop.reviews.count %>件のレビュー）
        </div>
      </div>
    </div>
  </div>
  <footer class="card-footer">
  <%= link_to movie_shop_reviews_path(movie_shop), class: "button card-footer-item" do %>
    レビューを見る
  <% end %>
  <%= link_to movie_shop_path(movie_shop), class: "button card-footer-item" do %>
    レビューを書く
  <% end %>
  </footer>
</div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/movie_shops/show.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="card mb-6">
          <header class="card-header">
            <p class="card-header-title">
              <%= @movie_shop.name %>
            </p>
          </header>
          <div class="card-content">
            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width: <%= @movie_shop.review_score_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= @movie_shop.avg_score %>点（<%= @movie_shop.reviews.count %>件のレビュー）
              </div>
            </div>
          </div>
        </div>
        <%= render 'reviews/form', review: @review, ramen_shop: @movie_shop %>
      </div>
    </div>
  </div>
</section>

app/views/reviews/_form.html.erb
<p class="is-size-4 mb-3">レビューを書く</p>

<% if review.errors.any? %>
  <div class="notification is-danger">
    <h2><%= review.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="rating-box mt-3">
  <%= form_with model: review, url: movie_shop_reviews_path(@movie_shop), local: true do |f| %>
    <div class="main-rating">
      <div class="ratings mb-3">
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
      </div>
      <div class="ml-3 rating-value-display"><span id="rating-value-display">0</span>/5</div>
    </div>
    <%= f.hidden_field :movie_shop_id, value: @movie_shop.id %>
    <%= f.hidden_field :score, id: "rating-value" %>
    <%= f.text_field :content, class: "textarea" %>
    <%= f.submit "保存", class: "button mt-3" %>
    <%= link_to "他のレビューを見る", movie_shop_reviews_path(@movie_shop), class: "button light ml-3 mt-3" %>
  <% end %>
</div>

<%= javascript_include_tag "reviews.js" %>

app/views/reviews/index.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="card mb-6">
          <header class="card-header">
            <p class="card-header-title">
              <%= @movie_shop.name %>
            </p>
          </header>
          <div class="card-content">
            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width: <%= @movie_shop.review_score_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= @movie_shop.avg_score %>点（<%= @movie_shop.reviews.count %>件のレビュー）
              </div>
            </div>
          </div>
        </div>
        <table class="table is-fullwidth has-text-centered">
          <thead>
            <tr>
              <th>ユーザー</th><th>点数</th><th>内容</th>
            </tr>
          </thead>
          <tbody>
            <% @reviews.each do |review| %>
              <tr>
                <td><%= review.user.username %></td>
                <td><%= review.score %></td>
                <td><%= review.content %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>